<?php
define('APP_DIR', DOCUMENT_ROOT . DIRECTORY_SEPARATOR . 'app');
define('CONFIG_DIR', APP_DIR . DIRECTORY_SEPARATOR . 'config');
define('RESOURCE_DIR', APP_DIR . DIRECTORY_SEPARATOR . 'resource');
define('SQLITE_DIR', RESOURCE_DIR . DIRECTORY_SEPARATOR . 'sqlite');
define('TEMPLATE_DIR', RESOURCE_DIR . DIRECTORY_SEPARATOR . 'template');
define('SRC_DIR', DOCUMENT_ROOT . DIRECTORY_SEPARATOR . 'src');
define('VENDOR_DIR', DOCUMENT_ROOT . DIRECTORY_SEPARATOR . 'vendor');
